name: Node CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm test
        env:
          CI: true
      - name: Get build version
        id: get-build-version
        run: echo "::set-output name=build-version::$(node -p "require('./package.json').version")"
        shell: bash
      - name: Tag repo
        uses: mstark5652/tag-repo@v0.2.0
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          build-version: ${{ steps.get-build-version.outputs.build-version }}
          build-message: 'New release'
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
